theme: jekyll-theme-minimal
logo: img/logo_dark_crop.png
title: Wolf Youth | Мы делаем музыку
description: "Hi there! We are Robert and&nbsp;Niktia, and&nbsp;we&nbsp;are&nbsp;making&nbsp;musik."
mywork: "Contact us:"
mailto: "hello@wolfyouth.ru"
google_analytics: UA-165620962-1
